START

In [30]:
import pandas as pd


In [31]:
data = pd.read_csv(r"D:\Numpy Folder\sample_csv.csv")

In [32]:
data

Index               Name  Age         City    Country   Occupation  Salary  \
0      1         John Smith   34     New York        USA     Engineer   75000   
1      2      Alice Johnson   28       London         UK      Teacher   45000   
2      3       Bob Williams   45        Paris     France       Doctor  120000   
3      4        Emily Brown   22       Sydney  Australia      Student       0   
4      5        David Jones   51        Tokyo      Japan      Manager   90000   
5      6      Sophia Garcia   39       Madrid      Spain       Artist   60000   
6      7  Michael Rodriguez   29      Toronto     Canada   Programmer   80000   
7      8    Olivia Martinez   62         Rome      Italy      Retired   25000   
8      9    Daniel Anderson   31       Berlin    Germany  Salesperson   55000   
9     10    Isabella Thomas   25  Mexico City     Mexico   Accountant   50000   

   Is_Married  Last_Visit  Rating  
0        True  2024-01-15     4.5  
1       False  2023-11-20     3.8  
2        True  2024-02-01     4.9  
3       False  2024-03-10     4.2  
4        True  2023-12-05     4.0  
5       False  2024-01-25     3.5  
6        True  2024-02-15     4.7  
7        True  2023-10-30     4.1  
8       False  2024-03-01     3.9  
9       False  2024-02-28     4.3

In [33]:
#1d array

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
#2d array
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [35]:
#matrix

import numpy as np 

Matrix = np.array([[1,2,3],
                [4,5,6]])

print(Matrix)


[[1 2 3]
 [4 5 6]]


In [36]:
#zeros array

import numpy as np

zeros = np.zeros(5)

print(zeros)

[0. 0. 0. 0. 0.]


In [37]:
#ones

import numpy as np

ones = np.ones((3,3))

print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
#full

import numpy as np

arr = np.full((5,5), 'She')

print(arr)

[['She' 'She' 'She' 'She' 'She']
 ['She' 'She' 'She' 'She' 'She']
 ['She' 'She' 'She' 'She' 'She']
 ['She' 'She' 'She' 'She' 'She']
 ['She' 'She' 'She' 'She' 'She']]


In [39]:
#arange
#creating sequence of number

import numpy as np

arr = np.arange(1,100,2)

print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [40]:
#creating identity matrix
#eye(size)

import numpy as np

arr  = np.eye(5)

print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
#shape
#number of row and column

import numpy as np

arr  = np.eye(5)

print(arr.shape)


(5, 5)


In [42]:
#size
#give us the number of element


import numpy as np

arr  = np.eye(5)

print(arr.size)

25


In [43]:
#Ndim number of dimenstion
#dtype data type of element

import numpy as np
arr = np.array([[1,2,3,43],
                [3,4,5,6]])

print(arr.ndim)
print(arr.dtype)

2
int64


In [44]:
#astype(type u want to convert)

import numpy as np 

arr =  np.array([[1.1, 2.2 , 3.3],
              [4.4,5.5,6.6]])

print(arr.astype(int))

[[1 2 3]
 [4 5 6]]


In [45]:
#math operation

import numpy as np

arr = np.eye(5,5)

print(arr *5)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [46]:
#mathematics


import numpy as np



arr = np.array([11,22,33,44,55,66,77,88,99,100])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))

595
59.5
100
11
30.137186331839274
908.25


In [47]:
#seeing single element
#arr[index][row]

import numpy as np

arr = np.array([[1,2,3,4],
       [5,6,7,8]])

print(arr[1][3])

8


In [48]:
#start stop step
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[1:-1:2])
print(arr[::-1])
print(arr[:7])#0 to 7 indes




[2 4 6 8]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7]


In [49]:
#Fancy indexing
# selecting multiple element at ones
#arr[index number ]

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[[0,5,9]])


[ 1  6 10]


In [50]:
#filtering data based on condition
#gives us true or false
#boolean masking

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[arr <11])

[1 2 3 4 5 6 7 8 9]


In [1]:
#reshape(row and columns)specify new shape if dimentions match

import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8,9,10])

new = arr.reshape(2,5)

print(new)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
#flating arrys
#converting multidimention into 1d array
#ravel()->views
#flatten ->copy

import numpy as np

arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

print(arr.ravel())
print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#inserting
#insert(index)
#np.insert(arrayName , index , value , asix = None)
#axis = 0 ,row wise
#  1 colmn wise

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

new = np.insert(arr , 10 , [11,12,13,14,15], axis = 0)

print(new)





[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
#2d

import numpy as np 

arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

new = np.insert(arr , 5 , [11,12], axis = 1 )

print(new)

[[ 1  2  3  4  5 11]
 [ 6  7  8  9 10 12]]


In [6]:
#apppend

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,22])
new =  np.append(arr , [23,2,4])
print(new)

[ 1  2  3  4  5  6  7  8  9 10 11 22 23  2  4]


In [7]:
#np.concatenate((arr1,arr2) , axis = 0 )
# 0 = vertical stacking
#1 means horizontal stacking

import numpy as np 
arr1 = np.array ([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

new_arr = np.concatenate((arr1 ,arr2))
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
#np.delete(arr name , index , axis = none)

import numpy as np

arr = np.array([[1,2,3,4],
       [5,6,7,8]])

new = np.delete(arr,0 , axis = 0)
print(new)


[[5 6 7 8]]


In [9]:
#stacking vstack = row , hstack = column

import numpy as np 
arr1 = np.array ([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
#split
#np.split()eqal
#np.hsplit(, np.vsplit()

import numpy as np 
arr1 = np.array ([1,2,3,4,5,6])

print(np.split(arr1 ,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [14]:
import numpy as np

# Create a 4x4 array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12], 
                [13, 14, 15, 16]])

# Split the array into 2 equal parts (2 rows each)
split_arrays = np.vsplit(arr, 2)

print(split_arrays)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [15]:
#boardcasting

import numpy as np 
arr1 = np.array ([100,200,300,400,500,600])
discount = 7 

price = arr1 - (arr1 *discount /100)

print(price)


[ 93. 186. 279. 372. 465. 558.]


In [16]:
import numpy as np

arr = np.array([[1,2,3,4],
       [5,6,7,8]])

vector  = np.array([7,8,9,10])

result = arr + vector
print(result)

[[ 8 10 12 14]
 [12 14 16 18]]
